Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.provision :shell, path: "bootstrap.sh"
  
	config.vm.provider "virtualbox" do |v|
			v.destroy_unused_network_interfaces = true
			v.memory = 2048
			v.cpus = 4
    end
end
