Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 8080, host: 9000, host_ip: "127.0.0.1"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y curl unzip maven --force-yes
	apt-get -y install mysql-server-5.7
	apt-get -y install mysql-client-core-5.7
    cd /vagrant/
    mvn spring-boot:run
  SHELL
end
